mutation CreateOfferForEmployee($createOfferForEmployeeInput: CreateOfferForEmployeeInput!) {
    createOfferForEmployee(createOfferForEmployeeInput: $createOfferForEmployeeInput) {
       ...DetailFullOfferForEmployee
    }
}