mutation UpdateOfferForEmployee($updateOfferForEmployeeId: String!, $updateOfferForEmployeeInput: UpdateOfferForEmployeeInput!) {
    updateOfferForEmployee(id: $updateOfferForEmployeeId, updateOfferForEmployeeInput: $updateOfferForEmployeeInput) {
        ...DetailFullOfferForEmployee
    }
}