mutation UpdateCustomer($updateCustomerId: String!, $updateCustomerInput: UpdateCustomerInput!) {
    updateCustomer(id: $updateCustomerId, updateCustomerInput: $updateCustomerInput) {
        ...FullCustomer
    }
}