fragment DetailFullOfferForEmployee on OfferForEmployeeType {
    id
    employee {
        ...DetailFullEmployee
    }
    offerForCompany {
        ...DetailFullOfferForCompany
    }
    booking {
        id
    }
}