mutation UpdateBooking($updateBookingId: String!, $updateBookingInput: UpdateBookingInput!) {
    updateBooking(id: $updateBookingId, updateBookingInput: $updateBookingInput) {
        ...DefaultBooking
    }
}
