mutation UpdateEmployee($updateEmployeeId: String!, $updateEmployeeInput: UpdateEmployeeInput!) {
    updateEmployee(id: $updateEmployeeId, updateEmployeeInput: $updateEmployeeInput) {
        ...DetailFullEmployee
    }
}