mutation CreateOfferForCompany($createOfferForCompanyInput: CreateOfferForCompanyInput!) {
    createOfferForCompany(createOfferForCompanyInput: $createOfferForCompanyInput) {
        ...DetailFullOfferForCompany
    }
}
