mutation UpdateOfferForCompany(
    $updateOfferForCompanyId: String!
    $updateOfferForCompanyInput: UpdateOfferForCompanyInput!
) {
    updateOfferForCompany(id: $updateOfferForCompanyId, updateOfferForCompanyInput: $updateOfferForCompanyInput) {
        ...DetailFullOfferForCompany
    }
}
