mutation CreateCompany($createCompanyInput: CreateCompanyInput!) {
    createCompany(createCompanyInput: $createCompanyInput) {
        address
        description
        email
        id
        imageId
        imageUrl
        name
        phoneNumber
     }
}
